name: Update server

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master

      - name: Update static file on server
        uses: appleboy/ssh-action@master
        with:
          host: new.dev.arthall.online
          username: root
          port: 65321
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /var/www/arthall/arthall.newback
            git fetch --all
            git reset --hard origin/master
            chmod 777 -R storage

            mkdir -p /etc/nginx/snippets/new.arthall/
            cp .deploy/prod/nginx/snippets/new.arthall/* /etc/nginx/snippets/new.arthall/
            cp .deploy/prod/nginx/new.arthall.online.conf /etc/nginx/conf.d/new.arthall.online.conf
            service nginx reload

            yes | composer install
            npm i

            cp .deploy/prod/.env /var/www/arthall/arthall.newback/.env
            php artisan key:generate
            php artisan migrate --force

            npm run dev
      - name: Release notification
        uses: appleboy/telegram-action@master
        with:
          to: "-1001704333037"
          token: 5219393533:AAHPlGYKhMEMeEx7Ho0MFsyH5i8VXtX6los
          message: |
            ${{ github.actor }} выкатил новый релиз на https://new.dev.arthall.online - ${{github.event.head_commit.message}}

